backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

# See https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "下書き", name: "draft", widget: "boolean", default: true}
      - {label: "本文", name: "body", widget: "markdown"}
  - name: "books" # Used in routes, e.g., /admin/collections/blog
    label: "Books" # Used in the UI
    folder: "data/books" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    extension: yml
    format: yml
    fields: # The fields for each document, usually in front matter
      - {label: "書籍名", name: "title", widget: "string"}
      - {label: "リンク先URL", name: "url", widget: "string"}
      - {label: "表紙画像 ( 横:縦=1:√2 | サイズは ~200 KB くらい | 形式は jpg か png )", name: "cover", widget: "image"}
      - {label: "リリース日", name: "date", widget: "date", format: "x"}
    editor:
      preview: false
  - name: "works" # Used in routes, e.g., /admin/collections/blog
    label: "Works" # Used in the UI
    folder: "data/works.yml" # The path to the folder where the documents are stored
    fields: # The fields for each document, usually in front matter
      - {label: "一行目", name: "first_line", widget: "string"}
      - {label: "二行目", name: "second_line", widget: "string"}
    editor:
      preview: false
